version: 2
jobs:
  build:
    docker:
      - image: ozawayut/twist-circleci
    working_directory: /go/src/github.com/tweeeety/twist-circleci
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: docker info run
          command: docker info
      - run:
          name: Directory Check
          command: |
            pwd
            ls -lR
      - run:
          name: docker image build
          command: docker build . 
      - run:
          name: docker image check
          command: docker images
